keys:
  - &users:
    - &xun age17pdqkpfh6kc6wm7gxzdnwf6vphlwddv9yfpdu3j76e24y3amd9tq3avfc8
  - &hosts:
    - &nixdesk age155sscpw0x36t6s9usdrz7relpxqrtqnk98mrc7s0qcv2n0v3zd7sfl2xn8
    - &hopper age1e9nhfwfcg9krc03re4fwh0wu0cwf6jq4js5vfn26hcdqc2apgdes98fea7

creation_rules:
  - path_regex: home/profiles/secrets
    key_groups:
      - age:
        - *xun
  - path_regex: sys/profiles/secrets/global
    key_groups:
      - age:
        - *xun
        - *nixdesk
        - *hopper
  - path_regex: sys/profiles/secrets/nixdesk
    key_groups:
      - age:
        - *xun
        - *nixdesk
  - path_regex: sys/profiles/secrets/hopper
    key_groups:
      - age:
        - *xun
        - *hopper
