keys:
  - &users:
    - &xun age17pdqkpfh6kc6wm7gxzdnwf6vphlwddv9yfpdu3j76e24y3amd9tq3avfc8
  - &hosts:
    - &nixdesk age155sscpw0x36t6s9usdrz7relpxqrtqnk98mrc7s0qcv2n0v3zd7sfl2xn8
    - &hopper age15mgf89h220puhz48rjpwxwu4n2h4edur60w6cd8gku2hh4e5kqpsghvnyw

creation_rules:
  - path_regex: secrets/global
    key_groups:
      - age:
        - *xun
        - *nixdesk
        - *hopper
  - path_regex: secrets/nixdesk
    key_groups:
      - age:
        - *xun
        - *nixdesk
  - path_regex: secrets/hopper
    key_groups:
      - age:
        - *xun
        - *hopper
