# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  krunker = {
    pname = "krunker";
    version = "1626868370902057";
    src = fetchurl {
      url = "https://client2.krunker.io/setup.AppImage";
      sha256 = "sha256-yG8E3a6AaX0TBK23TlBBLmiCfqzS8FldTfl7As4Dcvo=";
    };
  };
  sobercookie = {
    pname = "sobercookie";
    version = "35566d1a3354f0b9c975cc226b2eb49af0e088dc";
    src = fetchFromGitHub {
      owner = "xunuwu";
      repo = "sobercookie";
      rev = "35566d1a3354f0b9c975cc226b2eb49af0e088dc";
      fetchSubmodules = false;
      sha256 = "sha256-DOGH4eMnYyFzwSzz9FZZx6Nmzc5npIQmYDzCQ7+K76Q=";
    };
    date = "2024-09-14";
  };
}
