# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  sobercookie = {
    pname = "sobercookie";
    version = "0e082ab538a2eed206ab228ed50c5251323abdf2";
    src = fetchFromGitHub {
      owner = "xunuwu";
      repo = "sobercookie";
      rev = "0e082ab538a2eed206ab228ed50c5251323abdf2";
      fetchSubmodules = false;
      sha256 = "sha256-hdW/MqzphyAy6bcN3LDFFRV0t9ZHOx2b96hu9acZ7+E=";
    };
    date = "2024-09-08";
  };
}
